plugins:
- jekyll-email-protect

title: Challenges in Java
description: Coding challenges in java solved, tested and commented
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
author: mborzenkov
author_email: mborzenkov-dev@yandex.ru
repository: mborzenkov/Challenges-in-Java
url: https://mborzenkov.github.io/Challenges-in-Java/
email: 
exclude: [ demo.md ]